"""
/***************************************************************************
                        3DCityDb Tools for QGIS
 
        This is a QGIS plugin for the CityGML 3D City Database.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-30
        git sha              : $Format:%H$
        author(s)            : Giorgio Agugiaro
                               Konstantinos Pantelios
        email                : g.agugiaro@tudelft.nl
                               konstantinospantelios@yahoo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.gui import QgisInterface
from .cdb_tools_main import CDBToolsMain

def classFactory(iface: QgisInterface):
    """Load CDBToolsMain class from file cdb_tools_main.py

    *   :param iface: A QGIS interface instance.

        :type iface: QgsInterface
    """
    return CDBToolsMain(iface=iface)