# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/konstantinos/.local/share/QGIS/QGIS3/profiles/default/python/plugins/citydb_loader/citydb_loader_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DBLoaderDialogBase(object):
    def setupUi(self, DBLoaderDialogBase):
        DBLoaderDialogBase.setObjectName("DBLoaderDialogBase")
        DBLoaderDialogBase.resize(672, 541)
        DBLoaderDialogBase.setMinimumSize(QtCore.QSize(0, 0))
        DBLoaderDialogBase.setSizeGripEnabled(False)
        DBLoaderDialogBase.setModal(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DBLoaderDialogBase)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wdgMain = QtWidgets.QTabWidget(DBLoaderDialogBase)
        self.wdgMain.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgMain.sizePolicy().hasHeightForWidth())
        self.wdgMain.setSizePolicy(sizePolicy)
        self.wdgMain.setMinimumSize(QtCore.QSize(0, 0))
        self.wdgMain.setDocumentMode(False)
        self.wdgMain.setTabsClosable(False)
        self.wdgMain.setMovable(False)
        self.wdgMain.setTabBarAutoHide(False)
        self.wdgMain.setObjectName("wdgMain")
        self.tbConn = QtWidgets.QWidget()
        self.tbConn.setObjectName("tbConn")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tbConn)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.lblConnToExist = QtWidgets.QLabel(self.tbConn)
        self.lblConnToExist.setObjectName("lblConnToExist")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblConnToExist)
        self.btnConnToExist = QtWidgets.QComboBox(self.tbConn)
        self.btnConnToExist.setAccessibleName("")
        self.btnConnToExist.setAutoFillBackground(False)
        self.btnConnToExist.setEditable(False)
        self.btnConnToExist.setCurrentText("")
        self.btnConnToExist.setFrame(True)
        self.btnConnToExist.setObjectName("btnConnToExist")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btnConnToExist)
        self.lblOr = QtWidgets.QLabel(self.tbConn)
        self.lblOr.setObjectName("lblOr")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.lblOr)
        self.lblNewConn = QtWidgets.QLabel(self.tbConn)
        self.lblNewConn.setObjectName("lblNewConn")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblNewConn)
        self.btnNewConn = QtWidgets.QPushButton(self.tbConn)
        self.btnNewConn.setEnabled(True)
        self.btnNewConn.setCheckable(False)
        self.btnNewConn.setChecked(False)
        self.btnNewConn.setObjectName("btnNewConn")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnNewConn)
        self.verticalLayout.addLayout(self.formLayout_4)
        self.btnCeckCityDB = QtWidgets.QPushButton(self.tbConn)
        self.btnCeckCityDB.setObjectName("btnCeckCityDB")
        self.verticalLayout.addWidget(self.btnCeckCityDB)
        self.wdgMain.addTab(self.tbConn, "")
        self.tbImport = QtWidgets.QWidget()
        self.tbImport.setEnabled(False)
        self.tbImport.setObjectName("tbImport")
        self.gridLayout = QtWidgets.QGridLayout(self.tbImport)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.grbSchema = QtWidgets.QGroupBox(self.tbImport)
        self.grbSchema.setObjectName("grbSchema")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.grbSchema)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.lblScema = QtWidgets.QLabel(self.grbSchema)
        self.lblScema.setObjectName("lblScema")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblScema)
        self.cbxScema = gui.QgsCheckableComboBox(self.grbSchema)
        self.cbxScema.setObjectName("cbxScema")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbxScema)
        self.verticalLayout_7.addLayout(self.formLayout_9)
        self.verticalLayout_12.addWidget(self.grbSchema)
        self.grbFeature = QtWidgets.QGroupBox(self.tbImport)
        self.grbFeature.setObjectName("grbFeature")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.grbFeature)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.lvlFeature = QtWidgets.QLabel(self.grbFeature)
        self.lvlFeature.setObjectName("lvlFeature")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lvlFeature)
        self.qcbxFeature = gui.QgsCheckableComboBox(self.grbFeature)
        self.qcbxFeature.setObjectName("qcbxFeature")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.qcbxFeature)
        self.verticalLayout_10.addLayout(self.formLayout_10)
        self.verticalLayout_12.addWidget(self.grbFeature)
        self.grbGeometry = QtWidgets.QGroupBox(self.tbImport)
        self.grbGeometry.setObjectName("grbGeometry")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.grbGeometry)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.lblGeometryLvl = QtWidgets.QLabel(self.grbGeometry)
        self.lblGeometryLvl.setObjectName("lblGeometryLvl")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblGeometryLvl)
        self.cbxGeometryLvl = gui.QgsCheckableComboBox(self.grbGeometry)
        self.cbxGeometryLvl.setObjectName("cbxGeometryLvl")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbxGeometryLvl)
        self.verticalLayout_8.addLayout(self.formLayout_6)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.lblGeometryType = QtWidgets.QLabel(self.grbGeometry)
        self.lblGeometryType.setObjectName("lblGeometryType")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblGeometryType)
        self.cbxGeomteryType = gui.QgsCheckableComboBox(self.grbGeometry)
        self.cbxGeomteryType.setObjectName("cbxGeomteryType")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbxGeomteryType)
        self.verticalLayout_8.addLayout(self.formLayout_7)
        self.verticalLayout_12.addWidget(self.grbGeometry)
        self.grbExtent = QtWidgets.QGroupBox(self.tbImport)
        self.grbExtent.setObjectName("grbExtent")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.grbExtent)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formLayout_17 = QtWidgets.QFormLayout()
        self.formLayout_17.setObjectName("formLayout_17")
        self.qgrbExtent = gui.QgsExtentGroupBox(self.grbExtent)
        self.qgrbExtent.setObjectName("qgrbExtent")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.qgrbExtent)
        self.lblExtent = QtWidgets.QLabel(self.grbExtent)
        self.lblExtent.setObjectName("lblExtent")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblExtent)
        self.verticalLayout_9.addLayout(self.formLayout_17)
        self.verticalLayout_12.addWidget(self.grbExtent)
        self.gridLayout.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.wdgMain.addTab(self.tbImport, "")
        self.tbAbout = QtWidgets.QWidget()
        self.tbAbout.setObjectName("tbAbout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tbAbout)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 631, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.txtAbout = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.txtAbout.setObjectName("txtAbout")
        self.verticalLayout_13.addWidget(self.txtAbout)
        self.wdgMain.addTab(self.tbAbout, "")
        self.verticalLayout_2.addWidget(self.wdgMain)

        self.retranslateUi(DBLoaderDialogBase)
        self.wdgMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DBLoaderDialogBase)

    def retranslateUi(self, DBLoaderDialogBase):
        _translate = QtCore.QCoreApplication.translate
        DBLoaderDialogBase.setWindowTitle(_translate("DBLoaderDialogBase", "3DCityDB-Loader"))
        self.lblConnToExist.setText(_translate("DBLoaderDialogBase", "Select an existing connection:"))
        self.btnConnToExist.setToolTip(_translate("DBLoaderDialogBase", "uylilu"))
        self.lblOr.setText(_translate("DBLoaderDialogBase", "    or"))
        self.lblNewConn.setText(_translate("DBLoaderDialogBase", "Make new Connection:"))
        self.btnNewConn.setText(_translate("DBLoaderDialogBase", "New Connection"))
        self.btnCeckCityDB.setText(_translate("DBLoaderDialogBase", "Check 3DCityDb compatability of <DB>"))
        self.wdgMain.setTabText(self.wdgMain.indexOf(self.tbConn), _translate("DBLoaderDialogBase", "Connection"))
        self.grbSchema.setTitle(_translate("DBLoaderDialogBase", "Schema"))
        self.lblScema.setText(_translate("DBLoaderDialogBase", "Select Schema:"))
        self.grbFeature.setTitle(_translate("DBLoaderDialogBase", "Feature"))
        self.lvlFeature.setText(_translate("DBLoaderDialogBase", "Select feature:"))
        self.grbGeometry.setTitle(_translate("DBLoaderDialogBase", "Geometry"))
        self.lblGeometryLvl.setText(_translate("DBLoaderDialogBase", "Select geometry level:"))
        self.lblGeometryType.setText(_translate("DBLoaderDialogBase", "Select geometry type:"))
        self.grbExtent.setTitle(_translate("DBLoaderDialogBase", "Extent"))
        self.lblExtent.setText(_translate("DBLoaderDialogBase", "Select extent:"))
        self.wdgMain.setTabText(self.wdgMain.indexOf(self.tbImport), _translate("DBLoaderDialogBase", "Import"))
        self.txtAbout.setHtml(_translate("DBLoaderDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">name=3DCityDB-Loader</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">qgisMinimumVersion=3.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">description=This is an experimental plugin for 3DCityDB data visualization and manipulation.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">version=0.1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">author=Konstantinos Pantelios</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">email=konstantinospantelios@yahoo.com</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">about=Relational database are very good at storing and handling massive amount of data, however everyday users often find it hard to navigate, explore and work with data directly from the database. This plugin can be used to bring 3DCityDB data into the more widespread and straitforward world of QGIS.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">tracker=https://github.com/Konstantinos-Pantelios/3DCityDB-QGIS-Loader</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">repository=https://github.com/Konstantinos-Pantelios/3DCityDB-QGIS-Loader</p></body></html>"))
        self.wdgMain.setTabText(self.wdgMain.indexOf(self.tbAbout), _translate("DBLoaderDialogBase", "About"))
from qgis import gui
