-- ***********************************************************************
--
--      QGIS Package for the CityGML 3D City Database (for PostgreSQL)
--
--
--                        Copyright 2023
--
-- Delft University of Technology, The Netherlands
-- 3D Geoinformation Group
-- https://3d.bk.tudelft.nl/
-- 
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--     http://www.apache.org/licenses/LICENSE-2.0
--     
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- Author: Giorgio Agugiaro
-- Delft University of Technology, The Netherlands
-- 3D Geoinformation Group
-- https://3d.bk.tudelft.nl/gagugiaro/
--
-- ***********************************************************************
--
-- This script creates the config tables for enumerations and codelists.
-- current database, and the template tables.
--
-- ***********************************************************************


------------------------------------------------------------------
-- TABLE QGIS_PKG.ENUM_LOOKUP_CONFIG_TEMPLATE
------------------------------------------------------------------
CREATE TABLE qgis_pkg.enum_lookup_config_template(
id 					integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
ade_prefix 			varchar DEFAULT NULL,
source_class 		varchar, 
--source_table        varchar,
source_column 		varchar,
target_table 		varchar, -- 
key_column 			varchar NOT NULL,
value_column 		varchar NOT NULL,
filter_expression 	varchar,
num_columns 		integer DEFAULT 1,
allow_multi 		boolean DEFAULT FALSE,
allow_null 			boolean DEFAULT TRUE,
order_by_value 		boolean DEFAULT FALSE,
use_completer 		boolean DEFAULT FALSE,
description 		text
);
COMMENT ON TABLE qgis_pkg.enum_lookup_config_template IS 'Settings to set up look-up tables of enumerations in QGIS forms';
CREATE INDEX enluc_source_class_idx ON qgis_pkg.enum_lookup_config_template (source_class);
CREATE INDEX enluc_ade_prefix_idx   ON qgis_pkg.enum_lookup_config_template (ade_prefix);

INSERT INTO qgis_pkg.enum_lookup_config_template
(ade_prefix, source_class, source_column, target_table, key_column, value_column, filter_expression)
VALUES
(NULL, 'CityObject', 'relative_to_terrain', 'v_enumeration', 'value', 'description', 'data_model = ''CityGML 2.0'' AND name = ''RelativeToTerrainType'''),
(NULL, 'CityObject', 'relative_to_water'  , 'v_enumeration', 'value', 'description', 'data_model = ''CityGML 2.0'' AND name = ''RelativeToWaterType''')
;

------------------------------------------------------------------
-- TABLE QGIS_PKG.CODELIST_LOOKUP_CONFIG
------------------------------------------------------------------
CREATE TABLE qgis_pkg.codelist_lookup_config_template(
id 					integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
ade_prefix 			varchar DEFAULT NULL,
source_class 		varchar, -- CityObject
--source_table        varchar,
source_column 		varchar,
target_table 		varchar, -- 
key_column 			varchar NOT NULL,
value_column 		varchar NOT NULL,
filter_expression 	varchar,
num_columns 		integer DEFAULT 1,
allow_multi 		boolean DEFAULT FALSE,
allow_null 			boolean DEFAULT TRUE,
order_by_value 		boolean DEFAULT FALSE,
use_completer 		boolean DEFAULT FALSE,
description 		text
);
COMMENT ON TABLE qgis_pkg.codelist_lookup_config_template IS 'Settings to set up look-up tables of codelist in QGIS forms';

CREATE INDEX clluc_source_class_idx ON qgis_pkg.codelist_lookup_config_template (source_class);
CREATE INDEX clluc_ade_prefix_idx   ON qgis_pkg.codelist_lookup_config_template (ade_prefix);

-- INSERT INTO qgis_pkg.codelist_lookup_config_template
-- (ade_prefix, source_class, source_column, target_table, key_column, value_column, filter_expression)
-- VALUES
-- (NULL, 'CityObject', 'relative_to_terrain', 'v_enumeration', 'value', 'description', 'data_model = ''CityGML 2.0'' AND name = ''RelativeToTerrainType'''),
-- (NULL, 'CityObject', 'relative_to_water'  , 'v_enumeration', 'value', 'description', 'data_model = ''CityGML 2.0'' AND name = ''RelativeToWaterType''')
-- ;