
CREATE TABLE qgis_pkg.enum_link_config(
id 					integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
widget_type 		varchar, -- ValueRelation, etc.
source_class 		varchar, -- CityObject
source_column 		varchar,
target_table 		varchar, -- 
ade_prefix 			varchar DEFAULT NULL,
key_column 			varchar NOT NULL,
value_column 		varchar NOT NULL,
filter_expression 	varchar,
num_columns 		integer DEFAULT 1,
allow_multi 		boolean DEFAULT FALSE,
allow_null 			boolean DEFAULT TRUE,
order_by_value 		boolean DEFAULT FALSE,
use_completer 		boolean DEFAULT FALSE,
description 		text
);
COMMENT ON TABLE qgis_pkg.enum_link_config IS 'Settings to set up look-up tables in QGIS forms';
CREATE INDEX et_source_class_idx ON qgis_pkg.enum_link_config (source_class);
CREATE INDEX et_ade_prefix_idx   ON qgis_pkg.enum_link_config (ade_prefix);

INSERT INTO qgis_pkg.enum_link_config
(widget_type, source_class, source_column, target_table, key_column, value_column, filter_expression)
VALUES
('ValueRelation', 'CityObject', 'relative_to_terrain', 'v_enumeration', 'value', 'description', 'data_model = ''CityGML 2.0'' AND name = ''RelativeToTerrainType'''),
('ValueRelation', 'CityObject', 'relative_to_water', 'v_enumeration', 'value', 'description', 'data_model = ''CityGML 2.0'' AND name = ''RelativeToWaterType''')
;

CREATE TABLE qgis_pkg.children_table_config(
id			integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
rel_name		varchar,
rel_id			varchar,
rel_type		varchar,  -- Association or Composition
parent_class	varchar,
parent_layer	varchar,
parent_column	varchar,
child_class		varchar,
child_table		varchar,
child_column	varchar,
description 	text
);
COMMENT ON TABLE qgis_pkg.children_table_config IS 'Settings to set up look-up tables in QGIS forms';
