-- ***********************************************************************
--
--      QGIS Package for the CityGML 3D City Database (for PostgreSQL)
--
--
--                        Copyright 2023
--
-- Delft University of Technology, The Netherlands
-- 3D Geoinformation Group
-- https://3d.bk.tudelft.nl/
-- 
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--     http://www.apache.org/licenses/LICENSE-2.0
--     
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- Author: Giorgio Agugiaro
-- Delft University of Technology, The Netherlands
-- 3D Geoinformation Group
-- https://3d.bk.tudelft.nl/gagugiaro/
--
-- ***********************************************************************
--
-- This script creates the config tables for enumerations and codelists.
-- current database, and the template tables.
--
-- ***********************************************************************


------------------------------------------------------------------
-- TABLE QGIS_PKG.ENUM_LOOKUP_CONFIG_TEMPLATE
------------------------------------------------------------------
DROP TABLE IF EXISTS qgis_pkg.enum_lookup_config_template CASCADE;
CREATE TABLE         qgis_pkg.enum_lookup_config_template(
id 					integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
ade_prefix 			varchar DEFAULT NULL,
source_class 		varchar,
source_table        varchar,
source_column 		varchar,
target_table 		varchar, -- 
key_column 			varchar NOT NULL,
value_column 		varchar NOT NULL,
filter_expression 	varchar,
num_columns 		integer DEFAULT 1,
allow_multi 		boolean DEFAULT FALSE,
allow_null 			boolean DEFAULT TRUE,
order_by_value 		boolean DEFAULT TRUE,
use_completer 		boolean DEFAULT FALSE,
description 		text
);
COMMENT ON TABLE qgis_pkg.enum_lookup_config_template IS 'Settings to set up look-up tables of enumerations in QGIS forms';

CREATE INDEX enluc_ade_prefix_idx   ON qgis_pkg.enum_lookup_config_template (ade_prefix);
CREATE INDEX enluc_source_class_idx ON qgis_pkg.enum_lookup_config_template (source_class);


INSERT INTO qgis_pkg.enum_lookup_config_template
(ade_prefix, source_class, source_table, source_column, target_table, key_column, value_column, filter_expression)
VALUES
(NULL, 'CityObject', 'cityobject', 'relative_to_terrain', 'v_enumeration', 'value', 'description', 'data_model = ''CityGML 2.0'' AND name = ''RelativeToTerrainType'''),
(NULL, 'CityObject', 'cityobject', 'relative_to_water'  , 'v_enumeration', 'value', 'description', 'data_model = ''CityGML 2.0'' AND name = ''RelativeToWaterType''')
;

------------------------------------------------------------------
-- TABLE QGIS_PKG.CODELIST_LOOKUP_CONFIG_TEMPLATE
------------------------------------------------------------------
DROP TABLE IF EXISTS qgis_pkg.codelist_lookup_config_template CASCADE;
CREATE TABLE         qgis_pkg.codelist_lookup_config_template(
id 					integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name                varchar NOT NULL, -- a simple name to identify the group of codelists to load/use.
ade_prefix          varchar,
source_class 		varchar, -- Building, etc...
source_table        varchar,
source_column 		varchar,
target_table 		varchar, -- 
key_column          varchar NOT NULL,
value_column		varchar NOT NULL,
filter_expression	varchar,
num_columns 		integer DEFAULT 1,     -- number of columns entries are distributed in the form
allow_multi 		boolean DEFAULT FALSE, -- allows selection of multiple entries (for 0:* cardinality)
allow_null 			boolean DEFAULT TRUE,
order_by_value 		boolean DEFAULT TRUE,
use_completer 		boolean DEFAULT FALSE,
description 		text
);
COMMENT ON TABLE qgis_pkg.codelist_lookup_config_template IS 'Settings to set up look-up tables of codelists in QGIS forms';

CREATE INDEX clluc_name_idx        ON qgis_pkg.codelist_lookup_config_template (name);
CREATE INDEX clluc_ade_prefix_idx ON qgis_pkg.codelist_lookup_config_template (ade_prefix);

INSERT INTO qgis_pkg.codelist_lookup_config_template
(name, source_class, source_table, source_column, target_table, key_column, value_column, allow_multi, num_columns, filter_expression)
VALUES
---------------------------
-- CityGML 2.0 codelists as per specifications
---------------------------
-- Bridge
('CityGML 2.0', 'Bridge'      , 'bridge', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBridgeClass'''),
('CityGML 2.0', 'Bridge'      , 'bridge', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBridgeFunctionUsage'''),
('CityGML 2.0', 'Bridge'      , 'bridge', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBridgeFunctionUsage'''),
-- BridgePart
('CityGML 2.0', 'BridgePart'  , 'bridge', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBridgeClass'''),
('CityGML 2.0', 'BridgePart'  , 'bridge', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBridgeFunctionUsage'''),
('CityGML 2.0', 'BridgePart'  , 'bridge', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBridgeFunctionUsage'''),
-- Building
('CityGML 2.0', 'Building'    , 'building', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBuildingClass'''),
('CityGML 2.0', 'Building'    , 'building', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBuildingFunctionUsage'''),
('CityGML 2.0', 'Building'    , 'building', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBuildingFunctionUsage'''),
('CityGML 2.0', 'Building'    , 'building', 'roof_type' , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBuildingRoofType'''),
-- BuildingPart
('CityGML 2.0', 'BuildingPart', 'building', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBuildingClass'''),
('CityGML 2.0', 'BuildingPart', 'building', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBuildingFunctionUsage'''),
('CityGML 2.0', 'BuildingPart', 'building', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBuildingFunctionUsage'''),
('CityGML 2.0', 'BuildingPart', 'building', 'roof_type' , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractBuildingRoofType'''),
-- BuildingRoom
('CityGML 2.0', 'BuildingRoom', 'room', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''RoomClass'''),
('CityGML 2.0', 'BuildingRoom', 'room', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''RoomFunctionUsage'''),
('CityGML 2.0', 'BuildingRoom', 'room', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''RoomFunctionUsage'''),
-- BuildingFurniture
('CityGML 2.0', 'BuildingFurniture', 'building_furniture', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''BuildingFurnitureClass'''),
('CityGML 2.0', 'BuildingFurniture', 'building_furniture', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''BuildingFurnitureFunctionUsage'''),
('CityGML 2.0', 'BuildingFurniture', 'building_furniture', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''BuildingFurnitureFunctionUsage'''),
-- BuildingInstallation (outer)
('CityGML 2.0', 'BuildingInstallation', 'building_installation', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''BuildingInstallationClass'''),
('CityGML 2.0', 'BuildingInstallation', 'building_installation', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''BuildingInstallationFunctionUsage'''),
('CityGML 2.0', 'BuildingInstallation', 'building_installation', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''BuildingInstallationFunctionUsage'''),
-- BuildingInstallation (interior)
('CityGML 2.0', 'IntBuildingInstallation', 'building_installation', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''IntBuildingInstallationClass'''),
('CityGML 2.0', 'IntBuildingInstallation', 'building_installation', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''IntBuildingInstallationFunctionUsage'''),
('CityGML 2.0', 'IntBuildingInstallation', 'building_installation', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''IntBuildingInstallationFunctionUsage'''),
-- CityFurniture
('CityGML 2.0', 'CityFurniture', 'city_furniture', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''CityFurnitureClass'''),
('CityGML 2.0', 'CityFurniture', 'city_furniture', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''CityFurnitureFunctionUsage'''),
('CityGML 2.0', 'CityFurniture', 'city_furniture', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''CityFurnitureFunctionUsage'''),
-- CityObjectGroup
('CityGML 2.0', 'CityObjectGroup', 'cityobjectgroup', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''CityObjectGroupClass'''),
('CityGML 2.0', 'CityObjectGroup', 'cityobjectgroup', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''CityObjectGroupFunctionUsage'''),
('CityGML 2.0', 'CityObjectGroup', 'cityobjectgroup', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''CityObjectGroupFunctionUsage'''),
-- LandUse
('CityGML 2.0', 'LandUse', 'land_use', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''LandUseClass'''),
('CityGML 2.0', 'LandUse', 'land_use', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''LandUseFunctionUsage'''),
('CityGML 2.0', 'LandUse', 'land_use', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''LandUseFunctionUsage'''),
-- TransportationComplex
('CityGML 2.0', 'TransportationComplex', 'transportation_complex', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''TransportationComplexClass'''),
('CityGML 2.0', 'TransportationComplex', 'transportation_complex', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''TransportationComplexFunctionUsage'''),
('CityGML 2.0', 'TransportationComplex', 'transportation_complex', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''TransportationComplexFunctionUsage'''),
-- AuxiliaryTrafficArea
--('CityGML 2.0', 'AuxiliaryTrafficArea', 'traffic_area', 'class'            , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''AuxiliaryTrafficAreaClass'''),
('CityGML 2.0', 'AuxiliaryTrafficArea', 'traffic_area', 'function'         , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''AuxiliaryTrafficAreaFunction'''),
--('CityGML 2.0', 'AuxiliaryTrafficArea', 'traffic_area', 'usage'            , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''AuxiliaryTrafficAreaFunctionUsage'''),
('CityGML 2.0', 'AuxiliaryTrafficArea', 'traffic_area', 'surface_material' , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''TrafficAreaSurfaceMaterial'''),
-- TrafficArea
--('CityGML 2.0', 'TrafficArea', 'traffic_area', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''TrafficAreaClass'''),
('CityGML 2.0', 'TrafficArea', 'traffic_area', 'function'         , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''TrafficAreaFunction'''),
('CityGML 2.0', 'TrafficArea', 'traffic_area', 'usage'            , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''TrafficAreaUsage'''),
('CityGML 2.0', 'TrafficArea', 'traffic_area', 'surface_material' , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''TrafficAreaSurfaceMaterial'''),
-- Tunnel
('CityGML 2.0', 'Tunnel'      , 'tunnel', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractTunnelClass'''),
('CityGML 2.0', 'Tunnel'      , 'tunnel', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractTunnelFunctionUsage'''),
('CityGML 2.0', 'Tunnel'      , 'tunnel', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractTunnelFunctionUsage'''),
-- TunnelPart
('CityGML 2.0', 'TunnelPart'  , 'tunnel','class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractTunnelClass'''),
('CityGML 2.0', 'TunnelPart'  , 'tunnel','function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractTunnelFunctionUsage'''),
('CityGML 2.0', 'TunnelPart'  , 'tunnel','usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''_AbstractTunnelFunctionUsage'''),
-- PlantCover
('CityGML 2.0', 'PlantCover', 'plant_cover', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''PlantCoverClassFunctionUsage'''),
('CityGML 2.0', 'PlantCover', 'plant_cover', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''PlantCoverClassFunctionUsage'''),
('CityGML 2.0', 'PlantCover', 'plant_cover', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''PlantCoverClassFunctionUsage'''),
-- SolitaryVegetationObject
('CityGML 2.0', 'SolitaryVegetationObject', 'solitary_vegetat_object', 'class'   , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''SolitaryVegetationObjectClassFunctionUsage'''),
('CityGML 2.0', 'SolitaryVegetationObject', 'solitary_vegetat_object', 'function', 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''SolitaryVegetationObjectClassFunctionUsage'''),
('CityGML 2.0', 'SolitaryVegetationObject', 'solitary_vegetat_object', 'usage'   , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''SolitaryVegetationObjectClassFunctionUsage'''),
('CityGML 2.0', 'SolitaryVegetationObject', 'solitary_vegetat_object', 'species' , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''SolitaryVegetationObjectSpecies'''),
-- WaterBody
('CityGML 2.0', 'WaterBody', 'waterbody', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''WaterbodyClass'''),
('CityGML 2.0', 'WaterBody', 'waterbody', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''WaterbodyFunction'''),
('CityGML 2.0', 'WaterBody', 'waterbody', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''CityGML 2.0'' AND name = ''WaterbodyUsage'''),
-- WaterSurface
('CityGML 2.0', 'WaterSurface', 'waterboundary_surface', 'water_level', 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''CityGML 2.0'' AND name = ''WaterSurfaceWaterLevel'''),

---------------------------
-- TUD 3DGeoInfo Building
---------------------------
-- Building
('TUD-3DGeoinfo', 'Building'    , 'building', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''TUD-3DGeoinfo'' AND name = ''BAG_gebruiksdoel'''),
--('CityGML 2.0', 'Building'    , 'building', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''TUD-3DGeoinfo'' AND name = ''_AbstractBuildingFunctionUsage'''),
--('CityGML 2.0', 'Building'    , 'building', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''TUD-3DGeoinfo'' AND name = ''_AbstractBuildingFunctionUsage'''),
--('CityGML 2.0', 'Building'    , 'building', 'roof_type' , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''TUD-3DGeoinfo'' AND name = ''_AbstractBuildingRoofType'''),
-- BuildingPart
('TUD-3DGeoinfo', 'BuildingPart', 'building', 'class'     , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''TUD-3DGeoinfo'' AND name = ''BAG_gebruiksdoel''')
--('CityGML 2.0', 'BuildingPart', 'building', 'function'  , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''TUD-3DGeoinfo'' AND name = ''_AbstractBuildingFunctionUsage'''),
--('CityGML 2.0', 'BuildingPart', 'building', 'usage'     , 'v_codelist', 'value', 'description', TRUE , 3, 'data_model = ''TUD-3DGeoinfo'' AND name = ''_AbstractBuildingFunctionUsage'''),
--('CityGML 2.0', 'BuildingPart', 'building', 'roof_type' , 'v_codelist', 'value', 'description', FALSE, 1, 'data_model = ''TUD-3DGeoinfo'' AND name = ''_AbstractBuildingRoofType'''),
;